<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2SlugGenerator\Module'                                    => __DIR__ . '/Module.php',
  'Zf2SlugGenerator\Exception\SlugException'           => __DIR__ . '/src/Zf2SlugGenerator/Exception/SlugException.php',
  'Zf2SlugGenerator\Mapper\DbTable'                    => __DIR__ . '/src/Zf2SlugGenerator/Mapper/DbTable.php',
  'Zf2SlugGenerator\Mapper\Exception\DbTableException' => __DIR__ . '/src/Zf2SlugGenerator/Mapper/Exception/SlugDbException.php',
  'Zf2SlugGenerator\Service\Factory\SlugFactory'       => __DIR__ . '/src/Zf2SlugGenerator/Service/Factory/SlugFactory.php',
  'Zf2SlugGenerator\Service\Slug'                      => __DIR__ . '/src/Zf2SlugGenerator/Service/Slug.php',
);
